# Generated by Django 2.2.5 on 2019-09-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_musica', models.CharField(max_length=50, verbose_name='Nome da Musica')),
                ('nome_artista', models.CharField(max_length=50, verbose_name='Artista')),
                ('genero_musica', models.CharField(max_length=50, verbose_name='Genero')),
                ('link_musica', models.CharField(max_length=50, verbose_name='Link')),
            ],
        ),
    ]
